import type { SVGProps } from 'react'
import * as L from 'lucide-react'

type CompatIconProps = SVGProps<SVGSVGElement> & {
  size?: number | string
  weight?: string
}

function icon(Icon: L.LucideIcon) {
  return function LucideCompatIcon({ weight: _weight, ...props }: CompatIconProps) {
    return <Icon {...props} />
  }
}

export const Archive = icon(L.Archive)
export const ArrowCounterClockwise = icon(L.RotateCcw)
export const ArrowLeft = icon(L.ArrowLeft)
export const ArrowRight = icon(L.ArrowRight)
export const BellNotification = icon(L.Bell)
export const BellRinging = icon(L.BellRing)
export const Book = icon(L.BookOpen)
export const BookOpenText = icon(L.BookOpenText)
export const Building = icon(L.Building2)
export const BuildingOffice = icon(L.School)
export const Buildings = icon(L.Building2)
export const Camera = icon(L.Camera)
export const Calendar = icon(L.CalendarDays)
export const CalendarCheck = icon(L.CalendarCheck)
export const CalendarClock = icon(L.CalendarClock)
export const CalendarPlus = icon(L.CalendarPlus)
export const Car = icon(L.Car)
export const CarFront = icon(L.CarFront)
export const CarProfile = icon(L.CarFront)
export const Certificate = icon(L.BadgeCheck)
export const ChalkboardTeacher = icon(L.Presentation)
export const ChartLineUp = icon(L.ChartNoAxesColumnIncreasing)
export const Check = icon(L.Check)
export const CheckCircle = icon(L.CircleCheck)
export const ClipboardCheck = icon(L.ClipboardCheck)
export const Clock = icon(L.Clock)
export const Code = icon(L.Code2)
export const Compass = icon(L.Compass)
export const Copy = icon(L.Copy)
export const CreditCard = icon(L.CreditCard)
export const Dashboard = icon(L.Gauge)
export const EditPencil = icon(L.Pencil)
export const FileText = icon(L.FileText)
export const FloppyDiskArrowIn = icon(L.Save)
export const Funnel = icon(L.Funnel)
export const GearSix = icon(L.Settings)
export const Gift = icon(L.Gift)
export const GraduationCap = icon(L.GraduationCap)
export const GraphUp = icon(L.ChartNoAxesColumnIncreasing)
export const Group = icon(L.UsersRound)
export const Headset = icon(L.Headphones)
export const House = icon(L.House)
export const Inbox = icon(L.Inbox)
export const InfoCircle = icon(L.Info)
export const Key = icon(L.KeyRound)
export const Lightning = icon(L.Zap)
export const Link = icon(L.Link)
export const ListChecks = icon(L.ListChecks)
export const LockKey = icon(L.LockKeyhole)
export const LogOut = icon(L.LogOut)
export const MapPin = icon(L.MapPin)
export const MapTrifold = icon(L.Map)
export const Medal = icon(L.Medal)
export const Menu = icon(L.Menu)
export const MessageText = icon(L.MessageSquareText)
export const ChatCircleText = icon(L.MessageCircle)
export const NavArrowDown = icon(L.ChevronDown)
export const NavArrowLeft = icon(L.ChevronLeft)
export const NavArrowRight = icon(L.ChevronRight)
export const Note = icon(L.NotebookText)
export const OpenNewWindow = icon(L.ExternalLink)
export const Page = icon(L.FileText)
export const Palette = icon(L.Palette)
export const PaperPlaneTilt = icon(L.Send)
export const PencilSimple = icon(L.Pencil)
export const Phone = icon(L.Phone)
export const PhoneCall = icon(L.PhoneCall)
export const PlayCircle = icon(L.CirclePlay)
export const Plus = icon(L.Plus)
export const Puzzle = icon(L.Puzzle)
export const Refresh = icon(L.RefreshCw)
export const Reports = icon(L.FileSpreadsheet)
export const Search = icon(L.Search)
export const Send = icon(L.Send)
export const SendMail = icon(L.Mail)
export const Settings = icon(L.Settings)
export const ShieldAlert = icon(L.ShieldAlert)
export const ShieldCheck = icon(L.ShieldCheck)
export const SignIn = icon(L.LogIn)
export const SignOut = icon(L.LogOut)
export const Sparkle = icon(L.Sparkles)
export const Spinner = icon(L.LoaderCircle)
export const Student = icon(L.UserRound)
export const Trash = icon(L.Trash2)
export const Upload = icon(L.Upload)
export const User = icon(L.UserRound)
export const UserBadgeCheck = icon(L.UserCog)
export const UserCheck = icon(L.UserCheck)
export const UserCircle = icon(L.CircleUserRound)
export const UserPlus = icon(L.UserPlus)
export const WarningCircle = icon(L.CircleAlert)
export const WarningTriangle = icon(L.TriangleAlert)
export const Wallet = icon(L.Wallet)
export const X = icon(L.X)
export const XCircle = icon(L.CircleX)
export const Xmark = icon(L.X)
export const XmarkCircle = icon(L.CircleX)

export const InstructorFallbackIcon = icon(L.UserRound)
export const InstructorUnknownIcon = icon(L.BadgeQuestionMark)
